(load "src/lisp/init.lisp")
(load "test/lisp/test_framework.lisp")
(isiki-test-load "test/lisp/init_test.lisp")
(isiki-test-load "test/lisp/isiki_test.lisp")
;; リーダー構文依存の例は別ファイル。構文エラーでloadが中断した場合に検出できるよう
;; 戻り値(成功ならt)を確認する。loadの中でも assert-* が走るので、assert-equal の
;; 中にloadを直接書かず(isiki-test-beginの中断検出が入れ子を誤検出する)、いったん
;; 変数へ受けてから確認する
(defglobal *isiki-test-syntax-load-result* (isiki-test-load "test/lisp/isiki_test_syntax.lisp"))
(assert-equal t *isiki-test-syntax-load-result*)
;; 同じ仕様例を defun の本体にして JIT コンパイラに通す版(tools/gen_isiki_test_jit.py で生成)
(isiki-test-load "test/lisp/isiki_test_jit.lisp")
(isiki-test-load "test/lisp/za_test.lisp")
(isiki-test-load "test/lisp/za_test_ext5.lisp")
(isiki-test-load "test/lisp/za_test_ext7.lisp")
(isiki-test-load "test/lisp/za_test_ext8.lisp")
(isiki-test-load "test/lisp/za_test_ext9.lisp")
(isiki-test-load "test/lisp/za_test_ext10.lisp")
(isiki-test-load "test/lisp/za_test_ext11.lisp")
(isiki-test-load "test/lisp/za_test_ext12.lisp")
(isiki-test-load "test/lisp/za_test_ext13.lisp")
(isiki-test-load "test/lisp/za_test_ext14.lisp")
(isiki-test-load "test/lisp/za_test_ext15.lisp")
(isiki-test-load "test/lisp/za_test_ext16.lisp")
(isiki-test-load "test/lisp/za_test_ext17.lisp")
(isiki-test-load "test/lisp/za_test_ext18.lisp")
(isiki-test-load "test/lisp/za_test_ext19.lisp")
(isiki-test-load "test/lisp/environment_pages_test.lisp")
(isiki-test-load "test/lisp/environment_literal_slots_test.lisp")
(isiki-test-load "test/lisp/environment_utilities_test.lisp")
(isiki-test-load "test/lisp/room_test.lisp")
(isiki-test-load "test/lisp/aot_leaf_gc_test.lisp")
(isiki-test-load "test/lisp/za_code_imm_test.lisp")
(isiki-test-load "test/lisp/za_abi_probe_test.lisp")
(isiki-test-load "test/lisp/fn_cell_cache_test.lisp")
(isiki-test-load "test/lisp/frame_definition_test.lisp")
(isiki-test-load "test/lisp/frame_variable_test.lisp")
(isiki-test-load "test/lisp/frame_cell_gc_test.lisp")
(isiki-test-load "test/lisp/jit_nest_depth_test.lisp")
(isiki-test-load "test/lisp/jit_code_packing_test.lisp")
(isiki-test-load "test/lisp/declaim_test.lisp")
(isiki-test-load "test/lisp/inline_builtin_test.lisp")
(isiki-test-load "test/lisp/fixnum_signed_arith_test.lisp")
(isiki-test-load "test/lisp/single_float_test.lisp")
(isiki-test-load "test/lisp/float_contagion_test.lisp")
(isiki-test-load "test/lisp/float_math_contagion_test.lisp")
(isiki-test-load "test/lisp/convert_float_test.lisp")
(isiki-test-load "test/lisp/float_default_test.lisp")
(isiki-test-load "test/lisp/nan_comparison_test.lisp")
(isiki-test-load "test/lisp/divide_direct_call_test.lisp")
(isiki-test-load "test/lisp/declare_typed_add_test.lisp")
(isiki-test-load "test/lisp/declare_typed_sub_test.lisp")
(isiki-test-load "test/lisp/declare_typed_mul_test.lisp")
(isiki-test-load "test/lisp/declare_typed_div_test.lisp")
(isiki-test-load "test/lisp/declare_types_test.lisp")
(isiki-test-load "test/lisp/disassemble_test.lisp")

(isiki-test-report)
(close *isiki-test-stream*)
