(load "src/lisp/init.lisp")
(load "test/lisp/test_framework.lisp")
(load "src/lisp/device.lisp")
(load "src/lisp/ide.lisp")
(load "src/lisp/partition.lisp")
(load "src/lisp/fat32.lisp")
(load "src/lisp/mount.lisp")
(load "test/lisp/partition_test.lisp")

(isiki-test-report)
(close *isiki-test-stream*)
