(load "src/lisp/init.lisp")
(load "test/lisp/test_framework.lisp")
(load "test/lisp/za_test.lisp")
(load "test/lisp/fn_cell_cache_test.lisp")
(load "test/lisp/frame_definition_test.lisp")
(load "test/lisp/frame_variable_test.lisp")
(load "test/lisp/frame_cell_gc_test.lisp")
(load "test/lisp/jit_nest_depth_test.lisp")
(load "test/lisp/jit_code_packing_test.lisp")
(load "test/lisp/declaim_test.lisp")
(load "test/lisp/inline_builtin_test.lisp")
(load "test/lisp/fixnum_signed_arith_test.lisp")
(load "test/lisp/disassemble_test.lisp")

(isiki-test-report)
(close *isiki-test-stream*)
