;; マンデルブロ集合の描画
(defun mandelbrot ()
  (with-standard-output (open-output-stream)
    (for ((y -1.0 (+ y 0.05)))
         ((> y 1.0) t)
      (for ((x -2.0 (+ x 0.03)))
           ((> x 0.5) (let ((s (standard-output)))
                        (format-char s #\newline)))
        (let ((zr 0.0)
              (zi 0.0)
              (i 0)
              (hit nil))
          (for () ((or (> i 30) hit) nil)
            (let* ((zr2 (* zr zr))
                   (zi2 (* zi zi))
                   (c (+ zr2 zi2)))
              (if (> c 4.0)
                  (setq hit t)
                  (let* ((__zi (* 2.0 zr zi))
                         (_zi (+ __zi y))
                         (__zr (- zr2 zi2))
                         (_zr (+ __zr x))
                         (_i (+ i 1)))
                    (setq zi _zi)
                    (setq zr _zr)
                    (setq i _i)))))
          (let ((ch (if hit #\space #\*))
                (s (standard-output)))
            (format-char s ch)))))))
                       

