#!/usr/bin/env python3
"""Convert a BDF bitmap font into a C header of 8x16 glyph data.

Usage: python3 tools/gen_font.py <input.bdf> <output.h> [--range START END]

Each glyph is expected to be BBX 8 16 (8px wide, 16px tall, 1bpp, MSB=leftmost
pixel), matching boot.md 10-3's PSF v1-style font layout (16 bytes/glyph).
Codepoints in range without a glyph in the BDF are emitted as all-zero (blank).
"""

import sys


def parse_bdf(path, first, last):
    glyphs = {}
    with open(path, "r", encoding="ascii", errors="replace") as f:
        lines = f.read().splitlines()

    i = 0
    n = len(lines)
    while i < n:
        line = lines[i]
        if line.startswith("STARTCHAR"):
            encoding = None
            rows = []
            i += 1
            while i < n and not lines[i].startswith("ENDCHAR"):
                if lines[i].startswith("ENCODING"):
                    encoding = int(lines[i].split()[1])
                elif lines[i].startswith("BITMAP"):
                    i += 1
                    while i < n and not lines[i].startswith("ENDCHAR"):
                        rows.append(int(lines[i], 16))
                        i += 1
                    break
                i += 1
            if encoding is not None and first <= encoding <= last:
                rows = (rows + [0] * 16)[:16]
                glyphs[encoding] = rows
        i += 1
    return glyphs


def main():
    if len(sys.argv) < 3:
        sys.stderr.write(__doc__)
        sys.exit(1)

    in_path, out_path = sys.argv[1], sys.argv[2]
    first, last = 0, 127
    if "--range" in sys.argv:
        idx = sys.argv.index("--range")
        first, last = int(sys.argv[idx + 1]), int(sys.argv[idx + 2])

    glyphs = parse_bdf(in_path, first, last)
    count = last - first + 1

    with open(out_path, "w") as out:
        out.write("/* Generated by tools/gen_font.py from assets/fonts/spleen-8x16.bdf */\n")
        out.write("/* Spleen 8x16 -- Copyright (c) 2018-2026, Frederic Cambus -- BSD-2-Clause */\n")
        out.write("/* https://github.com/fcambus/spleen -- see assets/fonts/LICENSE */\n")
        out.write("/* 1 glyph = 16 rows x 1 byte, bit 7 = leftmost pixel */\n\n")
        out.write("#ifndef FONT8X16_H\n#define FONT8X16_H\n\n")
        out.write("static const unsigned char font8x16[%d][16] = {\n" % count)
        missing = []
        for code in range(first, last + 1):
            rows = glyphs.get(code)
            if rows is None:
                missing.append(code)
                rows = [0] * 16
            out.write("    {" + ",".join("0x%02X" % b for b in rows) + "}, /* 0x%02X */\n" % code)
        out.write("};\n\n#endif\n")

    if missing:
        sys.stderr.write("gen_font: no glyph for codepoints (emitted blank): %s\n" % missing)


if __name__ == "__main__":
    main()

